import mapper from 'object-mapper'

const mapping = {
  "id":                   "clearbit.id",
  "name.fullName":          "props.full_name", 
  "name.givenName":       "clearbit.given_name", 
  "name.familyName":        "props.last_name", 
  "email":                  "props.contact_email", 
  "gender":                 "props.gender", 
  "location":             "clearbit.location", 
  "utcOffset":            "clearbit.utcOffset", 
  "geo.city":               "props.address.city", 
  "geo.state":              "props.address.state", 
  "geo.stateCode":        "clearbit.stateCode", 
  "geo.country":            "props.address.country", 
  "geo.countryCode":      "clearbit.countryCode", 
  "geo.lat":              "clearbit.lat", 
  "geo.lng":              "clearbit.lng", 
  "bio":                    "props.description", 
  "site":                 "clearbit.site", 
  "avatar":                 "props.picture", 
  "employment.domain":    "clearbit.employment_domain", 
  "employment.name":      "clearbit.employment_name", 
  "employment.title":     "clearbit.employment_title", 
  "employment.role":      "clearbit.employment_role", 
  "employment.seniority": "clearbit.employment_seniority", 
  "facebook.handle":      "clearbit.facebook_handle", 
  "github.handle":        "clearbit.github_handle", 
  "github.avatar":        "clearbit.github_avatar", 
  "github.company":       "clearbit.github_company", 
  "github.blog":          "clearbit.github_blog", 
  "github.followers":     "clearbit.github_followers", 
  "github.following":     "clearbit.github_following", 
  "twitter.handle":       "clearbit.twitter_handle", 
  "twitter.id":           "clearbit.twitter_id", 
  "twitter.bio":          "clearbit.twitter_bio", 
  "twitter.followers":    "clearbit.twitter_followers", 
  "twitter.following":    "clearbit.twitter_following", 
  "twitter.location":     "clearbit.twitter_location", 
  "twitter.site":         "clearbit.twitter_site", 
  "twitter.avatar":       "clearbit.twitter_avatar", 
  "linkedin.handle":      "clearbit.linkedin_handle", 
  "googleplus.handle":    "clearbit.googleplus_handle", 
  "angellist.handle":     "clearbit.angellist_handle", 
  "angellist.bio":        "clearbit.angellist_bio", 
  "angellist.blog":       "clearbit.angellist_blog", 
  "angellist.site":       "clearbit.angellist_site", 
  "angellist.followers":  "clearbit.angellist_followers", 
  "angellist.avatar":     "clearbit.angellist_avatar", 
  "aboutme.handle":       "clearbit.aboutme_handle", 
  "aboutme.bio":          "clearbit.aboutme_bio", 
  "aboutme.avatar":       "clearbit.aboutme_avatar", 
  "gravatar.handle":      "clearbit.gravatar_handle", 
  "gravatar.avatar":      "clearbit.gravatar_avatar", 
  //"gravatar.urls[]":
  //"gravatar.avatars[]":
}

export default function(source){
  return mapper.merge(source, {}, mapping);
}
