import mapper from 'object-mapper'

const mapping = {
  "id":                   "cb.id",
  "name.fullName":          "props.full_name", 
  "name.givenName":       "cb.given_name", 
  "name.familyName":        "props.last_name", 
  "email":                  "props.contact_email", 
  "gender":                 "props.gender", 
  "location":             "cb.location", 
  "utcOffset":            "cb.utcOffset", 
  "geo.city":               "props.address.city", 
  "geo.state":              "props.address.state", 
  "geo.stateCode":        "cb.stateCode", 
  "geo.country":            "props.address.country", 
  "geo.countryCode":      "cb.countryCode", 
  "geo.lat":              "cb.lat", 
  "geo.lng":              "cb.lng", 
  "bio":                    "props.description", 
  "site":                 "cb.site", 
  "avatar":                 "props.picture", 
  "employment.domain":    "cb.employment_domain", 
  "employment.name":      "cb.employment_name", 
  "employment.title":     "cb.employment_title", 
  "employment.role":      "cb.employment_role", 
  "employment.seniority": "cb.employment_seniority", 
  "facebook.handle":      "cb.facebook_handle", 
  "github.handle":        "cb.github_handle", 
  "github.avatar":        "cb.github_avatar", 
  "github.company":       "cb.github_company", 
  "github.blog":          "cb.github_blog", 
  "github.followers":     "cb.github_followers", 
  "github.following":     "cb.github_following", 
  "twitter.handle":       "cb.twitter_handle", 
  "twitter.id":           "cb.twitter_id", 
  "twitter.bio":          "cb.twitter_bio", 
  "twitter.followers":    "cb.twitter_followers", 
  "twitter.following":    "cb.twitter_following", 
  "twitter.location":     "cb.twitter_location", 
  "twitter.site":         "cb.twitter_site", 
  "twitter.avatar":       "cb.twitter_avatar", 
  "linkedin.handle":      "cb.linkedin_handle", 
  "googleplus.handle":    "cb.googleplus_handle", 
  "angellist.handle":     "cb.angellist_handle", 
  "angellist.bio":        "cb.angellist_bio", 
  "angellist.blog":       "cb.angellist_blog", 
  "angellist.site":       "cb.angellist_site", 
  "angellist.followers":  "cb.angellist_followers", 
  "angellist.avatar":     "cb.angellist_avatar", 
  "aboutme.handle":       "cb.aboutme_handle", 
  "aboutme.bio":          "cb.aboutme_bio", 
  "aboutme.avatar":       "cb.aboutme_avatar", 
  "gravatar.handle":      "cb.gravatar_handle", 
  "gravatar.avatar":      "cb.gravatar_avatar", 
  //"gravatar.urls[]":
  //"gravatar.avatars[]":
}

export default function(source){
  return mapper.merge(source, {}, mapping);
}
